Add optional `serde` support for keys and PASERK IDs
brycx/pasetors pull request #71
Opened 2022-10-13 19:50 UTC by SanchithHegde

This PR introduces a `serde` feature which enables the `serde` support for keys to be de/serialized from/to PASERK strings, and PASERK IDs from/to strings. The corresponding unit tests have also been updated. 

Closes #26.

2022-10-13 19:55 UTC, SanchithHegde commented on src/paserk.rs
> +impl TryFrom<&str> for Id {
This implementation feels naive to me, let me know if you can think of a better approach.

2022-10-14 07:17 UTC, brycx requested changes
This is great work! Thanks for pushing this so far already. 

Apart from the specific comments, a general one is that `docsrs` spits out some errors during when building docs (`RUSTDOCFLAGS='--cfg docsrs' cargo +nightly doc --no-deps --all-features`) which need to be fixed

2022-10-14 07:17 UTC, brycx commented on src/paserk.rs
> +mod serde;
I'd like to either move `paserk.rs` into `paserk/` as `mod.rs` or move `serde.rs` out of its folder. Right now, we have a `paserk` module from the file __and__ the folder.

2022-10-14 07:17 UTC, brycx commented on src/paserk.rs
> +impl TryFrom<&str> for Id {
A simple straight-forward approach is oftentimes preferable. It looks good so far, but I'll think about it a bit more.

If you want to, it would be awesome to have the `From<Key>`/`TryFrom<&str>` fully a part of the PASERK fuzzing target as well. Right now it only includes `From<Key>`. Let me know if you want to or not and if you don't I'll create a new issue so that I can get it added.

2022-10-14 07:17 UTC, brycx commented on src/paserk/serde.rs
> +impl<V> serde::Serialize for AsymmetricPublicKey<V>
Please add `#![cfg_attr(docsrs, doc(cfg(feature = "serde")))]` to each impl of `Serialize` and `Deserialize` such that the documentation generates the correct feature tags for the functionality

2022-10-14 07:17 UTC, brycx commented on src/paserk.rs
> +                            let key_hex = key.clone();
Can we gate `let key_hex = key.clone()` under `paserk` features as well? Or maybe re-use the original value in another way? I would like to have the unused warnings removed

2022-10-14 18:03 UTC, SanchithHegde commented on src/paserk.rs
> +mod serde;
I've moved `serde` to a top-level module considering that there might be more `Serialize`/`Deserialize` implementations that might be added to it on a later date, which might not be PASERK-specific.

2022-10-15 15:17 UTC, SanchithHegde commented on src/paserk.rs
> +impl TryFrom<&str> for Id {
I've pushed a commit which adds `Id: TryFrom<&str>` to the PASERK fuzzing target. Let me know if it's different from what you expected.

2022-10-15 18:39 UTC, brycx commented on src/paserk.rs
> +mod serde;
This is great. I'll make it a private module after merging though, as it doesn't need to be public in the crate root rn, so long it only contains the trait implementations.

2022-10-15 18:41 UTC, brycx approved these changes
LGTM. Thanks a lot for working on this @SanchithHegde!

2022-10-15 18:41 UTC, merged